name: 'Install Dependencies'
description: 'Install project dependencies'

inputs:
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.14.0'

    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm@9.4.0

    - name: Check if pnpm-lock.yaml has changed
      id: check-pnpm-lock
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { execSync } = require('child_process');
          const fs = require('fs');

          const pnpmLockChanged = execSync('git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep pnpm-lock.yaml').includes('pnpm-lock.yaml');
          core.setOutput('pnpmLockChanged', pnpmLockChanged);

    - name: Clear Cache
      if: ${{ steps.check-pnpm-lock.outputs.pnpmLockChanged == 'true' }}
      uses: jhonnyvargasarias/actions/clear-ref-cache@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get pnpm store path
      id: pnpm-store-path
      shell: bash
      run: |
        echo "pnpm store path: $(pnpm store path)"
        echo "store-path=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Cache pnpm store and node_modules
      id: pnpm-cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.pnpm-store-path.outputs.store-path }}
          node_modules
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install
