name: Check coverage

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: jhonnyvargasarias/portfolio/.github/actions/install-dependencies@main

    - name: Check coverage
      shell: bash
      run: pnpm exec vitest --coverage --watch false
