name: 'Download Build Version'
description: 'Download the build version and set it as an environment variable'

runs:
  using: 'composite'
  steps:
    - name: Download version
      uses: actions/download-artifact@v3
      with:
        name: build-version

    - name: Set version environment variable
      shell: bash
      run: |
        BUILD_VERSION=$(cat build-version.txt)
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        if [ -z "$BUILD_VERSION" ]; then
          echo "Failed to set BUILD_VERSION environment variable"
          exit 1
        fi
