name: 'Upload Build Version'
description: 'Upload the build version as an artifact'

runs:
  using: 'composite'
  steps:
    - name: Set current build version
      shell: bash
      run: |
        BUILD_VERSION=$(date +'%Y.%m.%d.%H.%M.%S')
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV

    - name: Print build version
      shell: bash
      run: |
        echo "Build version: $BUILD_VERSION"

    - name: Set build version artifact
      shell: bash
      run: |
        if [ -z "$BUILD_VERSION" ]; then
          echo "Failed to set BUILD_VERSION environment variable"
          exit 1
        fi
        echo "$BUILD_VERSION" > build-version.txt

    - name: Upload build version
      uses: actions/upload-artifact@v3
      with:
        name: build-version
        path: build-version.txt
