name: Check prettier

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Check prettier
      shell: bash
      run: pnpm exec prettier --check --ignore-unknown .
