name: Check prettier

inputs:
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      uses: jhonnyvargasarias/portfolio/.github/actions/install-dependencies@main
      with:
        github-token: ${{ inputs.github-token }}

    - name: Check prettier
      shell: bash
      run: pnpm exec prettier --check --ignore-unknown .
