name: Check prettier

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Check prettier
      shell: bash
      run: |
        STAGED_FILES=$(git diff --cached --name-only --diff-filter=d)
        echo "$STAGED_FILES" | xargs pnpm exec prettier --check --ignore-unknown
        if [ $? -ne 0 ]; then
          exit 1
        fi
