name: Run tests

inputs:
  github-token:
    description: 'GitHub token'
    required: true

  sops-kms-arn:
    description: 'SOPS KMS ARN'
    required: true

  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true

  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true

  aws-default-region:
    description: 'AWS Default Region'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: jhonnyvargasarias/portfolio/.github/actions/install-dependencies@main
      with:
        github-token: ${{ inputs.github-token }}

    - name: Setup SOPS
      uses: nhedger/setup-sops@v2

    - name: Run SOPS
      shell: bash
      run: |
        sops --version

    - name: Prepare variables
      shell: bash
      run: |
        sops --output .env.local --decrypt .env.staging.encrypted
      env:
        SOPS_KMS_ARN: ${{ inputs.sops-kms-arn }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-default-region }}

    - name: Run tests
      shell: bash
      run: pnpm exec vitest --watch false
