name: Run tests

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: jhonnyvargasarias/portfolio/.github/actions/install-dependencies@main

    - name: Run tests
      shell: bash
      run: pnpm exec vitest --watch false
