name: Check linter

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      uses: jhonnyvargasarias/portfolio/.github/actions/install-dependencies@main

    - name: Check linter
      shell: bash
      run: pnpm exec next lint
