name: Check linter

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Check linter
      shell: bash
      run: pnpm exec next lint
