name: 'Update Prerelease to Release'
description: 'Update the prerelease to a release on success'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download release ID
      uses: ./.github/actions/download-release-id

    - name: Update pre-release to release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        RELEASE_ID: ${{ env.RELEASE_ID }}
      shell: bash
      run: |
          curl -s -X PATCH -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}" \
            -d '{"draft": false, "prerelease": false}'
