name: Deploy production
run-name: Deploy production

on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

concurrency:
  group: deploy-production-group-lock

jobs:
  generate-next-version:
    name: Generate next version
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.generate-next-version.outputs.next_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate next version
        id: generate-next-version
        uses: jhonny17/actions/generate-next-version@main
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          max_patch_version: 10
          max_minor_version: 10

  create-tag-and-pre-release:
    name: Create tag and pre-release
    runs-on: ubuntu-latest
    needs: generate-next-version
    outputs:
      release_id: ${{ steps.create-tag-and-pre-release-step.outputs.release_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tag and pre-release
        id: create-tag-and-pre-release-step
        uses: jhonny17/actions/create-tag-and-pre-release@main
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          build_version: ${{ needs.generate-next-version.outputs.next_version }}

  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: create-tag-and-pre-release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build project
        run: pnpm build

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: ${{ secrets.BUILD_OUTPUT_DIRECTORY }}
          gitHubToken: ${{ secrets.PAT_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch_name }}

  publish_release_on_sucess:
    name: Publish Release on Success
    runs-on: ubuntu-latest
    needs: [create-tag-and-pre-release, publish]
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update pre-release to release
        uses: ./update-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ needs.create-tag-and-pre-release.outputs.release_id }}
          prerelease: false
          draft: false

  delete_release_on_failure:
    name: Delete Release on Failure
    runs-on: ubuntu-latest
    needs: [generate-next-version, create-tag-and-pre-release, publish]
    if: ${{ failure() || cancelled() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete release
        uses: jhonny17/actions/delete-release@main
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          release_id: ${{ needs.create-tag-and-pre-release.outputs.release_id }}

      - name: Delete tag
        uses: jhonny17/actions/delete-tag@main
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          build_version: ${{ needs.generate-next-version.outputs.next_version }}
