name: Deploy staging

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  actions: write
  contents: write
  deployments: write

concurrency:
  group: deploy-staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-code-checks:
    name: Run code checks
    uses: jhonnyvargasarias/portfolio/.github/workflows/run-code-checks.yml@main
    secrets: inherit

  publish:
    name: Publish to Cloudflare Pages
    needs: run-code-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: jhonnyvargasarias/portfolio/.github/actions/install-dependencies@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2

      - name: Run SOPS
        run: |
          sops --version

      - name: Prepare variables
        continue-on-error: true
        run: |
          sops --output .env --decrypt .env.staging.encrypted
        env:
          SOPS_KMS_ARN: ${{ secrets.SOPS_KMS_ARN}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Build project
        run: pnpm build

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ secrets.BUILD_OUTPUT_DIRECTORY }} --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
