name: On Pull Request Closed

on:
  pull_request:
    types: [closed]

permissions:
  actions: write

jobs:
  clear_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clear Cache
        uses: jhonnyvargasarias/actions/clear-cache@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'refs/pull/${{ github.event.pull_request.number }}/merge'
