name: Run code checks

on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

concurrency:
  group: run-code-checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_prettier:
    name: Check prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check prettier
        uses: ./.github/actions/check-prettier

  check_lint:
    name: Check linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check eslint
        uses: ./.github/actions/check-linter

  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [check_prettier, check_lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: ./.github/actions/run-tests

  check_coverage:
    name: Check coverage
    runs-on: ubuntu-latest
    needs: [run_tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check coverage
        uses: ./.github/actions/check-coverage
