name: Run code checks

on:
  workflow_call:

permissions:
  contents: write
  deployments: write

concurrency:
  group: run-code-checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_prettier:
    name: Check prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check prettier
        uses: jhonnyvargasarias/portfolio/.github/actions/check-prettier@main

  check_lint:
    name: Check linter
    needs: check_prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check eslint
        uses: jhonnyvargasarias/portfolio/.github/actions/check-linter@main

  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: check_prettier
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: jhonnyvargasarias/portfolio/.github/actions/run-tests@main

  check_coverage:
    name: Check coverage
    runs-on: ubuntu-latest
    needs: check_prettier
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check coverage
        uses: jhonnyvargasarias/portfolio/.github/actions/check-coverage@main
