name: Version bump
run-name: Version bump

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      patch-level:
        description: 'The level of patch version to increment'
        required: false
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  deployments: write

concurrency:
  group: bump-version-group-lock
  cancel-in-progress: true

jobs:
  run-code-checks:
    name: Run code checks
    uses: jhonnyvargasarias/portfolio/.github/workflows/run-code-checks.yml@main
    secrets: inherit

  generate-next-version:
    name: Generate next version
    runs-on: ubuntu-latest
    needs: run-code-checks
    outputs:
      next_version: ${{ steps.generate-next-version.outputs.next_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate next version
        id: generate-next-version
        uses: jhonnyvargasarias/actions/generate-next-version@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          max_patch_version: 10
          max_minor_version: 10
          increment_minor_version: ${{ github.event.inputs.patch-level == 'minor' }}
          increment_major_version: ${{ github.event.inputs.patch-level == 'major' }}

  push-next-version:
    name: Push next version
    runs-on: ubuntu-latest
    needs: generate-next-version
    outputs:
      is_up_to_date: ${{ steps.check-package-json.outputs.is_up_to_date }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update package.json version
        id: check-package-json
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { exec } = require('@actions/exec');
            const { version } = require('./package.json');
            const nextVersion = '${{ needs.generate-next-version.outputs.next_version }}';

            if (version !== nextVersion) {
              await exec('npm', ['version', '--no-git-tag-version', nextVersion]);
              await exec('git', ['add', 'package.json']);
              await exec('git', ['config', '--global', 'user.name', '"github-actions[bot]"']);
              await exec('git', ['config', '--global', 'user.email', '"github-actions[bot]@users.noreply.github.com"']);
              await exec('git', ['commit', '-am', '"v${{ needs.generate-next-version.outputs.next_version }}"']);
              await exec('git', ['push', 'origin', 'main']);
            }

            core.setOutput('is_up_to_date', version === nextVersion);

  deploy_production:
    name: Deploy to production
    needs: [generate-next-version, push-next-version]
    if: ${{ needs.push-next-version.outputs.is_up_to_date == 'true' }}
    uses: jhonnyvargasarias/portfolio/.github/workflows/deploy-production.yml@main
    secrets: inherit
    with:
      next_version: ${{ needs.generate-next-version.outputs.next_version }}
